[profile.default]
src = "src"
out = "out"
via_ir = true
optimizer = true
optimizer_runs = 200

libs = ["lib"]
remappings = [
  "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[dependencies]
openzeppelin-contracts = { version = "4.9.3", default-features = false }
